# apt

- defaults:
    shell:
      stdout: true
      stderr: true

- shell:
    - description: Update packages
      command: sudo apt update && sudo apt -y upgrade && sudo apt -y autoremove
    - description: Install `aptitude`
      command: sudo apt install -y aptitude
    - description: Install list of packages from file
      command: sudo aptitude install -y $(cat ./dotfiles/apt/packages)
    - description: Install other packages with sophisticated steps
      command: ./dotfiles/apt/install
