# GitHub CLI

- link:
    ~/.config/gh: dotfiles/gh/*

- shell:
    - description: Install GitHub CLI extensions
      command: cat ./dotfiles/gh/extensions | xargs -L1 gh extension install 2>/dev/null || true
