# Homebrew

- link:
    # Generate from `brew bundle dump --global --force --describe`
    ~/.Brewfile: dotfiles/homebrew/Brewfile

- shell:
    # - description: Install Homebrew
    #   command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    #   stdin: true
    #   stdout: true
    #   stderr: true
    - description: Install all Homebrew packages and macOS apps
      command: command -v brew >/dev/null 2>&1 && brew bundle --global --verbose --no-lock
      stdin: true
      stdout: true
      stderr: true
