# Homebrew

- link:
    # Generate from `brew bundle dump --global --force --describe`
    ~/.Brewfile: dotfiles/homebrew/Brewfile

- shell:
    - description: Install Homebrew
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      stdin: true
    - description: Install all Homebrew packages and macOS apps
      command: |
        [ -x /usr/local/bin/brew ] && eval "$(/usr/local/bin/brew shellenv)"
        [ -x /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"
        command -v brew >/dev/null 2>&1 && brew bundle --global --verbose --no-lock || true
