# Homebrew on Linux

- link:
    # Generate from `brew bundle dump --global --force --describe`
    ~/.Brewfile: dotfiles/linuxbrew/Brewfile

- shell:
    - description: Install Homebrew on Linux
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      stdin: true
    - description: Install all Homebrew packages and macOS apps
      command: |
        [ -x ~/.linuxbrew/bin/brew ] && eval "$(~/.linuxbrew/bin/brew shellenv)"
        [ -x /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        command -v brew >/dev/null 2>&1 && brew bundle --global --verbose --no-lock || true
