# macOS

- shell:
    - description: Press `Cmd + Ctrl` and click anywhere on a window to move it
      command: defaults write -g NSWindowShouldDragOnGesture -bool true
    - description: Set Launchpad grid layout to 9x5
      command: >
        defaults write com.apple.dock springboard-columns -int 9 &&
        defaults write com.apple.dock springboard-rows -int 5 &&
        defaults write com.apple.dock -bool TRUE &&
        killall Dock
