# PowerShell

- link:
    ~/.config/powershell/Microsoft.PowerShell_profile.ps1: dotfiles/powershell/Microsoft.PowerShell_profile.ps1
    ~/.config/powershell/PoshThemes: dotfiles/powershell/PoshThemes
    ~/.config/powershell/Modules/UserModules: dotfiles/powershell/Modules/UserModules/*

- ifanylinux:
    - shell:
        - description: Install PowerShell modules
          command: >
            pwsh
            -NoProfile
            -NoLogo
            -NonInteractive
            -Command '
            Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;
            Install-Module -Name PSReadline -Force -Scope CurrentUser;
            Install-Module -Name z,Terminal-Icons,PsFzf -Repository PSGallery -Confirm:$False -Scope CurrentUser;
            '
          stdin: true
          stdout: true
          stderr: true

- ifmacos:
    - shell:
        - description: Install PowerShell modules
          command: >
            pwsh
            -NoProfile
            -NoLogo
            -NonInteractive
            -Command '
            Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;
            Install-Module -Name PSReadline -Force -Scope CurrentUser;
            Install-Module -Name z,Terminal-Icons,PsFzf -Repository PSGallery -Confirm:$False -Scope CurrentUser;
            '
          stdin: true
          stdout: true
          stderr: true
