# PowerShell

- link:
    ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1: dotfiles/powershell/Microsoft.PowerShell_profile.ps1
    ~/Documents/WindowsPowerShell/PoshThemes: dotfiles/powershell/PoshThemes
    ~/Documents/WindowsPowerShell/Modules/UserModules: dotfiles/powershell/Modules/UserModules/*

- shell:
    - description: Install PowerShell modules
      command: >
        powershell.exe
        -NoProfile
        -NoLogo
        -NonInteractive
        -Command "
        @(
        'posh-git',
        'PsFzf',
        'PSReadline',
        'Terminal-Icons',
        'z'
        ) | ForEach-Object {
        if (-not (Get-InstalledModule $_ -ErrorAction SilentlyContinue)) { Install-Module $_ -Repository PSGallery -Scope CurrentUser -Force } }
        "
      stdin: true
      stdout: true
      stderr: true

- shell:
    - description: Set XDG environment variables
      command: >
        powershell.exe
        -NoProfile
        -NoLogo
        -NonInteractive
        -Command "
        [Environment]::SetEnvironmentVariable(\"XDG_CONFIG_HOME\", \"$env:USERPROFILE\.config\", \"User\");
        [Environment]::SetEnvironmentVariable(\"XDG_CACHE_HOME\", \"$env:USERPROFILE\.cache\", \"User\");
        [Environment]::SetEnvironmentVariable(\"XDG_STATE_HOME\", \"$env:USERPROFILE\.local\state\", \"User\");
        [Environment]::SetEnvironmentVariable(\"XDG_DATA_HOME\", \"$env:USERPROFILE\.local\share\", \"User\");
        "
      stdin: true
      stdout: true
      stderr: true
