# PowerShell

- link:
    ~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1: dotfiles/powershell/Microsoft.PowerShell_profile.ps1
    ~/Documents/WindowsPowerShell/Modules/UserModules: dotfiles/powershell/Modules/UserModules/*

- shell:
    - description: Install PowerShell modules
      command: >
        powershell.exe
        -NoProfile
        -NoLogo
        -NonInteractive
        -Command "
        Install-PackageProvider -Name NuGet -Force;
        @(
        'posh-git',
        'PsFzf',
        'PSReadline',
        'Terminal-Icons',
        'z'
        ) | ForEach-Object {
        if (-not (Get-InstalledModule $_ -ErrorAction SilentlyContinue)) { Install-Module $_ -Repository PSGallery -Scope CurrentUser -Force } }
        "
