# Windows

- shell:
    - description: Set XDG environment variables
      command: >
        powershell.exe
        -NoProfile
        -NoLogo
        -NonInteractive
        -Command "
        [Environment]::SetEnvironmentVariable(\"XDG_CONFIG_HOME\", \"$env:USERPROFILE\.config\", \"User\");
        [Environment]::SetEnvironmentVariable(\"XDG_CACHE_HOME\", \"$env:USERPROFILE\.cache\", \"User\");
        [Environment]::SetEnvironmentVariable(\"XDG_STATE_HOME\", \"$env:USERPROFILE\.local\state\", \"User\");
        [Environment]::SetEnvironmentVariable(\"XDG_DATA_HOME\", \"$env:USERPROFILE\.local\share\", \"User\");
        "

- shell:
    - description: Hide some directories in Home
      command: >
        powershell.exe
        -NoProfile
        -NoLogo
        -NonInteractive
        -Command "Get-ChildItem -Path ~ -Filter .* | ForEach-Object { $_.Attributes += \"Hidden\" }"

- shell:
    - description: Set natural scrolling for mouses
      command: >
        powershell.exe
        -NoProfile
        -NoLogo
        -NonInteractive
        -Command "
        $mouseDevices = Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Enum\HID\*\*\Device Parameters' FlipFlopWheel -ErrorAction SilentlyContinue;
        foreach ($device in $mouseDevices) { Set-ItemProperty $device.PSPath FlipFlopWheel 1 }
        "
