# Windows Terminal

# Check if we can use built-in sync feature
# - https://github.com/microsoft/terminal/issues/2933
# - https://github.com/microsoft/terminal/issues/6687
# - https://github.com/microsoft/terminal/issues/4566

- link:
    $LOCALAPPDATA/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json: dotfiles/wt/settings.json
