#!/usr/bin/env bash

#: Check if all files in a Git repo are specified in the .gitattributes file

missing_attributes=$(git ls-files | git check-attr -a --stdin | grep "text: auto")
if [[ "$missing_attributes" ]]; then
    echo ".gitattributes rule missing for the following files:"
    echo "$missing_attributes"
else
    echo "All files have a corresponding rule in .gitattributes"
fi
