repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        exclude: '^home/.*$'
      - id: check-shebang-scripts-are-executable
        exclude: '^home/.*$'

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format --force-exclude
        language: system
        types_or: [python, pyi]

      - id: dprint
        name: dprint
        entry: mise x -- dprint fmt --allow-no-files
        language: system
        types: [text]

      - id: shellcheck
        name: shellcheck
        entry: mise x -- shellcheck
        language: system
        types: [shell]

      - id: markdownlint-cli2
        name: markdownlint-cli2
        entry: mise x -- markdownlint-cli2 --fix
        language: system
        types: [markdown]

      - id: ty
        name: ty
        entry: uv run ty check
        language: system
        types_or: [python, pyi]
