#!/usr/bin/env bash

# Exit immediately if an error occurs
set -e

# Go to the project directory
cd "$(dirname "$BASH_SOURCE")"

# Profiles and configs paths
META_DIR="$PWD/meta"
CONFIG_DIR="$META_DIR/configs"
PROFILES_DIR="$META_DIR/profiles"
BASE_CONFIG_PATH="$META_DIR/base.yaml"

# Dotbot paths
DOTBOT_DIR="$PWD/dotbot"
DOTBOT_BIN="$DOTBOT_DIR/bin/dotbot"
DOTBOT_PLUGINS_DIR="$PWD/plugins"

# Update Dotbot submodule
git -C "$DOTBOT_DIR" submodule sync --quiet --recursive
git submodule update --init --recursive

usage() {
    echo "Usage: $0 command"
    echo
    echo "Commands:"
    echo "  profile     Install by profile"
    echo "    $0 profile <profile> [<config>...]"
    echo
    echo "  config      Install by configs"
    echo "    $0 config <config> [<config>...]"
    echo "    <config>-sudo: Install with sudo"
}

case "$1" in
profile)
    profile_name=$2
    [[ -z "$profile_name" ]] && {
        usage
        exit 1
    }
    shift 2
    ;;
config)
    shift
    [[ -z "$@" ]] && {
        usage
        exit 1
    }
    ;;
*)
    usage
    exit 1
    ;;
esac

# Synthesize configs
configs=''
while read -r line; do
    # Ignore line starting with '#'
    [[ "$line" =~ ^\#.*$ ]] && continue
    configs="$configs $line"
done <"$PROFILES_DIR/$profile_name"
configs="$configs $@"

# Add all Dotbot plugins
plugin_args=''
for plugin_dir in $DOTBOT_PLUGINS_DIR/*; do
    [[ -d "$plugin_dir" ]] || continue
    plugin_args+="--plugin-dir $plugin_dir"
done

# Loop though configs and execute each with base config
for config in $configs; do
    echo "Configure $config"

    # Check if config file readable
    config_path="$CONFIG_DIR/${config%-sudo}.yaml"
    [[ ! -r "$config_path" ]] && {
        echo "Ignoring unknown config: $config_path"
        continue
    }

    # Create a temporary config file with base config and current config
    tempfile="$(mktemp)"
    cat "$BASE_CONFIG_PATH" "$config_path" >"$tempfile"

    # Allows execute a config as a superuser with sudo suffix, i.e. `bash-sudo`
    if [[ $config == *sudo* ]]; then
        sudo "$DOTBOT_BIN" -d "$PWD" -c "$tempfile" $plugin_args
    else
        "$DOTBOT_BIN" -d "$PWD" -c "$tempfile" $plugin_args
    fi

    rm -f "$tempfile"
done
