#!/usr/bin/env bash

# Configuration root relative filepath
CONFIG="install.conf.yaml"

# Dotbot root relative filepaths
DOTBOT_DIR="dotbot"
DOTBOT_BIN="$DOTBOT_DIR/bin/dotbot"

# Exit immediately if an error occurs
set -e

# Go to the project directory
cd "$(dirname "$BASH_SOURCE")"

# Update Dotbot submodule
git -C "$DOTBOT_DIR" submodule sync --quiet --recursive
git submodule update --init --recursive "$DOTBOT_DIR"

# Run Dotbot
"$PWD/$DOTBOT_BIN" -d "$PWD" -c "$PWD/$CONFIG" "${@}"
