# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
# :schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-yaml" },
    { id = "check-added-large-files" },
    { id = "check-case-conflict" },
    { id = "check-merge-conflict" },
    { id = "check-executables-have-shebangs", exclude = '^home/.*$' },
    { id = "check-shebang-scripts-are-executable", exclude = '^home/.*$' },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff-check"
entry = "uv run ruff check --force-exclude --fix"
language = "system"
types_or = ["python", "pyi"]

[[repos.hooks]]
id = "ruff-format"
name = "ruff-format"
entry = "uv run ruff format --force-exclude"
language = "system"
types_or = ["python", "pyi"]

[[repos.hooks]]
id = "dprint"
name = "dprint"
entry = "mise x -- dprint fmt --allow-no-files"
language = "system"
types = ["text"]

[[repos.hooks]]
id = "shellcheck"
name = "shellcheck"
entry = "mise x -- shellcheck"
language = "system"
exclude = '^home/dot_config/shell/zsh\.d/.*\.zsh$'
types = ["shell"]

[[repos.hooks]]
id = "shellcheck-usage"
name = "shellcheck (usage scripts)"
entry = "mise x -- shellcheck"
language = "system"
files = '^home/dot_local/bin/executable_dot-'

[[repos.hooks]]
id = "zsh-n"
name = "zsh -n"
entry = "bash -c 'for file do zsh -n \"$file\" || exit; done' --"
language = "system"
files = '^home/dot_config/shell/zsh\.d/.*\.zsh$'
types = ["shell"]

[[repos.hooks]]
id = "markdownlint-cli2"
name = "markdownlint-cli2"
entry = "mise x -- markdownlint-cli2 --fix"
language = "system"
types = ["markdown"]

[[repos.hooks]]
id = "ty"
name = "ty"
entry = "uv run ty check"
language = "system"
types_or = ["python", "pyi"]
