[project]
name = "dotfiles"
version = "0.0.0"
description = "Dotfiles for configuring my development environment"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-html>=4.2.0",
]

[tool.ruff]
extend-exclude = []
fix = true
line-length = 100

[tool.ruff.format]
skip-magic-trailing-comma = true
