#! /usr/bin/env bash

set -euo pipefail

case "$CHEZMOI_ARCH" in
arm64) HOMEBREW_PREFIX="/opt/homebrew" ;;
amd64)
    if [[ "$CHEZMOI_OS" == darwin ]]; then
        HOMEBREW_PREFIX="/usr/local"
    else
        HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
    fi
    ;;
esac

BREW_BIN="$HOMEBREW_PREFIX/bin/brew"

[[ -x "$BREW_BIN" ]] || {
    url=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    /bin/bash -c "$(curl -fsSL $url)"
    if [[ -x "$BREW_BIN" ]]; then
        eval "$("$BREW_BIN" shellenv)"
    else
        echo 'Failed to install Homebrew'
        exit 1
    fi
}

exec "$BREW_BIN" bundle \
    --verbose \
    --no-lock \
    --file {{ . | quote }}
