#!/bin/bash
# The shebang above is for shellcheck to check this file
#: vim: set fileencoding=utf-8 colorcolumn=81 nospell:

#: Source common profile configurations
common_profile="$HOME/.config/shell/common_profile"
if [[ -f "$common_profile" ]] && [[ -r "$common_profile" ]]; then
    # shellcheck source=dot_config/shell/common_profile
    . "$common_profile"
fi
unset common_profile
