#!/bin/bash
# The shebang above is for shellcheck to check this file
#: vim: set fileencoding=utf-8 colorcolumn=81 nospell:

#: Source common profile configurations
common_profile="$HOME/.config/shell/common_profile"
if [[ -f "$common_profile" ]] && [[ -r "$common_profile" ]]; then
    # shellcheck source=dot_config/shell/common_profile
    . "$common_profile"
fi
unset common_profile

#: OrbsStack {{{

# Added by OrbStack: command-line tools and integration
if [[ -f ~/.orbstack/shell/init.zsh ]]; then
    . ~/.orbstack/shell/init.zsh 2>/dev/null || :
fi

#: }}}
