#!/bin/bash
# The shebang above is for shellcheck to check this file
#: vim: set fileencoding=utf-8 colorcolumn=81 nospell:

#: Reference: https://git.julian.maurice.name/jajm/dotfiles

#: Source .zprofile if not already sourced (makes `zsh -i` equivalent to `zsh -il`)
if [[ ! -o login ]]; then
    zprofile="$HOME/.zprofile"
    if [[ -f "$zprofile" ]] && [[ -r "$zprofile" ]]; then
        # shellcheck source=dot_zprofile
        . "$zprofile"
    fi
    unset zprofile
fi

#: Source the common shell pre-configuration
common_rc_pre="$HOME/.config/shell/common_rc_pre"
if [[ -f "$common_rc_pre" ]] && [[ -r "$common_rc_pre" ]]; then
    # shellcheck source=dot_config/shell/common_rc_pre
    # shellcheck disable=SC2317
    . "$common_rc_pre" zsh || return 0
fi
unset common_rc_pre

#: Aliases {{{

alias zshout='zsh -is eval "unset HISTFILE"'

#: }}}

#: Shell settings {{{

#: Let me kill less of words
#: Don't consider '/', '-', '.', '=' is parts of words
#: Disable warning as we don't intend to make it available in child processes
# shellcheck disable=SC2034
WORDCHARS='*?_[]~&;!#$%^(){}<>'

#: Auto push previous directory to stack, `popd` to get back
setopt AUTO_PUSHD

#: }}}

#: History {{{

#: Change location of history file
HISTFILE="$SHELL_CACHE_DIR/history"
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

#: Can't still understand this but added to check later
#: Record timestamp of command in HISTFILE
setopt EXTENDED_HISTORY
#: Delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
#: Ignore duplicated commands history list
setopt HIST_IGNORE_DUPS
#: Ignore commands that start with space
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
#: Show command with history expansion to user before running it
setopt HIST_VERIFY
#: Add commands to HISTFILE in order of execution
setopt INC_APPEND_HISTORY
#: Share command history data
# setopt SHARE_HISTORY

#: }}}

#: Keybindings {{{

#: Use Alt + left/right to move by words
bindkey "\e[1;3D" backward-word
bindkey "\e[1;3C" forward-word
#: Use Alt + delete to delete forward word
bindkey "\e[3;3~" kill-word

#: Use up and down arrows for prefix history command searching
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

#: Use Cmd-delete or Cmd-fn-delete to delete to the beginning/end of line
#: Cannot find a keybinding for Cmd-delete
# bindkey '' backward-kill-line
bindkey '\e[3;9~' kill-line

#: Enable Shift-Tab to reverse in menu complete
bindkey '\e[Z' reverse-menu-complete

#: Ctrl-x Ctrl-e to open editor mode
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

#: }}}

#: Completion {{{

#: Brew autocompletion
if type brew &>/dev/null; then
    FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

#: Case insensitive completion
zstyle ':completion:*' matcher-list \
    'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' \
    'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' \
    'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' \
    'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

#: Change location of `.zcompcache` folder
zstyle ':completion:*' cache-path "$USER_CACHE_DIR/zsh/completions"

#: Force single tab completion
setopt nolistambiguous

#: Complete hidden files and folders
setopt globdots

#: Glob stars
setopt globstarshort

#: Add a folder for user completions
[ -d "$SHELL_CONFIG_DIR/completions" ] && FPATH="$SHELL_CONFIG_DIR/completions:${FPATH}"

#: Partial completion suggestions
zstyle ':completion:*' list-suffixeszstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' menu select

#: }}}

#: Tools {{{

#: pinentry-mac {{{

#: Follow this tutorial:
#: https://github.com/jorgelbg/pinentry-touchid/issues/3#issuecomment-915440261
command_exists pinentry-mac && alias pinentry=pinentry-touchid

#: }}}

#: kitty {{{

#: Shell integration
if [[ -n "$KITTY_INSTALLATION_DIR" ]]; then
    export KITTY_SHELL_INTEGRATION="no-rc no-title"
    autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
    kitty-integration
    unfunction kitty-integration
fi

#: }}}

#: Zsh plugins {{{

command_exists brew && {
    #: Fish-like autosuggestions 'zsh-autosuggestions'
    include "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
    #: Fish shell like syntax highlighting 'zsh-syntax-highlighting'
    #: Only enable it when not in VSCode terminal as it messes up when AI
    #: inserts long text
    [ "$TERM_PROGRAM" != vscode ] && include "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
}

#: }}}

#: }}}

#: Miscellaneous {{{

#: Something related to setting colors I don't know
autoload -U colors && colors

#: Build completion
#: If wanna run `compinit` only every 24 hours, see:
#: https://gist.github.com/ctechols/ca1035271ad134841284
autoload -Uz compinit && compinit -d "$SHELL_CACHE_DIR/completion"

#: }}}

#: Source the common shell post-configuration
common_rc_post="$HOME/.config/shell/common_rc_post"
if [ -f "$common_rc_post" ] && [ -r "$common_rc_post" ]; then
    # shellcheck source=dot_config/shell/common_rc_post
    . "$common_rc_post" "$@"
fi
unset common_rc_post
