- defaults:
    link:
      create: true
      glob: true
      relink: true
    shell:
      stdout: true
      stderr: true

- clean:
    ~/:
    ~/.config:
      recursive: true
    ~/.local:
      recursive: true

- create:
    ~/.cache:
