#! /usr/bin/env bash

set -euo pipefail

#
# dlvhdr/gh-dash
# vilmibm/gh-screensaver

if ! command -v gh &>/dev/null; then
    echo "gh is not installed"
    exit 1
fi

while read -r extension; do
    gh extension install "$extension" 2>/dev/null || true
done < "$CHEZMOI_SOURCE_DIR/private_dot_config/gh/.extensions"
