profiles:
  defaults:
    linux: linux-desktop
    darwin: darwin-personal
    windows: windows-desktop

  choices:
    linux:
      - linux-desktop
      - linux-workstation
      - linux-vm-dev
      - linux-minimal
    darwin:
      - darwin-personal
      - darwin-work
      - darwin-agent
    windows:
      - windows-desktop

  entries:
    linux-desktop:
      features:
        linux:
          install:
            apt:
              enabled: true
              manifests:
                - linux-desktop
            homebrew:
              enabled: true
              manifests:
                - linux-desktop
            flatpak:
              enabled: true
              manifests:
                - linux-desktop
          desktop:
            gnome:
              enabled: true
              extensions:
                manifests:
                  - linux-desktop
              settings:
                manifests:
                  - linux-desktop

    linux-workstation:
      features:
        linux:
          install:
            apt:
              enabled: true
              manifests:
                - linux-workstation
            homebrew:
              enabled: true
              manifests:
                - linux-workstation
            flatpak:
              enabled: true
              manifests:
                - linux-workstation
          desktop:
            gnome:
              enabled: true
              extensions:
                manifests:
                  - linux-workstation
              settings:
                manifests:
                  - linux-workstation

    linux-minimal:
      defaults:
        personal: false
        vault: ''
        headless: true
        shared: true
        hasSudo: false
        gitName: ''
        gitEmail: ''
        gitSigningKey: ''
      features:
        linux:
          install:
            apt:
              enabled: false
              manifests: []
            homebrew:
              enabled: true
              manifests:
                - linux-minimal
            flatpak:
              enabled: false
              manifests: []
          desktop:
            gnome:
              enabled: false
              extensions:
                manifests: []
              settings:
                manifests: []
            account_avatar:
              enabled: false
          system:
            rtc_local_time:
              enabled: false
          security:
            sudoers_disable_admin_flag:
              enabled: false
          network:
            ufw:
              enabled: false
          services:
            ssh_server:
              enabled: false
            xrdp:
              enabled: false
            code_server:
              enabled: false

    linux-vm-dev:
      defaults:
        headless: true
      features:
        linux:
          install:
            apt:
              enabled: true
              manifests: []
              repositories:
                onepassword:
                  enabled: false
                google_chrome:
                  enabled: false
                vscode:
                  enabled: false
                powershell:
                  enabled: false
                docker:
                  enabled: false
                ibus_bamboo:
                  enabled: false
                cloudflare_warp:
                  enabled: true
                cloudflared:
                  enabled: true
                openvpn3:
                  enabled: false
            homebrew:
              enabled: true
              manifests:
                - linux-vm-dev
            flatpak:
              enabled: false
              manifests: []
          desktop:
            gnome:
              enabled: false
              extensions:
                manifests: []
              settings:
                manifests: []
          security:
            sudo_ssh_agent_auth:
              enabled: true

    darwin-personal:
      defaults:
        client: true
      features:
        darwin:
          install:
            homebrew:
              enabled: true
              manifests:
                - darwin-personal

    darwin-work:
      features:
        darwin:
          install:
            homebrew:
              enabled: true
              manifests:
                - darwin-work

    darwin-agent:
      defaults:
        agent: true
        vault: CLU
        gitName: CLU
        gitEmail: clu@thanhph111.com
        gitSigningKey: ''
      features:
        darwin:
          install:
            homebrew:
              enabled: true
              manifests:
                - darwin-agent

    windows-desktop:
      features:
        windows:
          install:
            winget:
              enabled: true
              manifests:
                - windows-desktop.json
            scoop:
              enabled: true
              manifests:
                - windows-cli
