#!/bin/sh

#: Check if a file readable and source it without repeating filepath
include() {
    # shellcheck disable=SC1090,SC2015
    [ -r "$1" ] && [ -f "$1" ] && . "$1" || true
}

#: Check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

#: Environment variables for applications respecting XDG specifications {{{

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"

#: }}}

#: Force UTF-8 usage {{{

#: Might use `update-locale` instead
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#: }}}

#: terminfo {{{

export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"

#: }}}

#: Wget {{{

#: Change history file location
# shellcheck disable=SC2139
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"

#: }}}

#: Kvantum {{{

#: Use Kvantum to override Qt style
export QT_STYLE_OVERRIDE=kvantum

#: }}}

#: IBus Bamboo {{{

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
#: For Qt4 application
export QT4_IM_MODULE=ibus
#: For Clutter/OpenGL application
export CLUTTER_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus

#: }}}

#: GNU Readline {{{

#: Change initialization file location, not sure if it works
export INPUTRC="$HOME/.config/readline/inputrc"

#: }}}

#: Homebrew {{{

if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
elif [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

command_exists brew && {
    #: Do not clean old version
    # export HOMEBREW_NO_CLEANUP_FORMULAE=oh-my-posh

    #: Do not show cleanup hint
    export HOMEBREW_NO_ENV_HINTS=1

    #: Opt out Google Analytics
    export HOMEBREW_NO_ANALYTICS=1

    #: Forbid redirects from secure HTTPS to insecure HTTP
    export HOMEBREW_NO_INSECURE_REDIRECT=1

    #: Require all casks to have a checksum
    export HOMEBREW_CASK_OPTS=--require-sha
}

#: }}}

#: Nix {{{

#: Install with `sh <(curl -L https://nixos.org/nix/install) --no-daemon --no-modify-profile`
include "$HOME/.nix-profile/etc/profile.d/nix.sh"

#: }}}

#: Secretive {{{

#: Only on macOS
#: SSH Agent forwarding in VSCode Dev Container without creating LaunchAgents
#: Reference: https://github.com/maxgoedjen/secretive/blob/main/APP_CONFIG.md.
if [ -S "$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh" ]; then
    export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
elif [ -S "$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ]; then
    export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
fi

#: }}}

#: GnuPG {{{

export GNUPGHOME="$XDG_DATA_HOME/gnupg"

#: }}}

#: AWS {{{

#: Workaround to move AWS config to XDG_CONFIG_HOME until this issue is fixed:
#: https://github.com/aws/aws-sdk/issues/30
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
export AWS_CLI_HISTORY_FILE="$XDG_CONFIG_HOME/aws/history"
export AWS_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
#: For some reason Terraform doesn't like the `AWS_WEB_IDENTITY_TOKEN_FILE`
#: variable, causing it to throw this: `WebIdentityErr: role ARN is not set`
#: so you'd better not export it if not necessary.
# export AWS_WEB_IDENTITY_TOKEN_FILE="$XDG_CONFIG_HOME/aws/token"
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/shared-credentials"

#: Opt out AWS SAM CLI telemetry
export SAM_CLI_TELEMETRY=0

#: }}}

#: Rust {{{

export RUSTUP_HOME="$XDG_CACHE_HOME/rustup"
export CARGO_HOME="$XDG_CACHE_HOME/cargo"

command_exists cargo && {
    include "$CARGO_HOME/env"
    export PATH="$CARGO_HOME/bin:$PATH"
}

#: }}}

#: Go {{{

command_exists go && {
    export GOPATH="$XDG_DATA_HOME/go"
    export PATH="$GOPATH/bin:$PATH"
}

#: }}}

#: PowerShell {{{

export POWERSHELL_UPDATECHECK=Off
export POWERSHELL_TELEMETRY_OPTOUT=1

#: }}}

#: Node.js {{{

export NODE_REPL_HISTORY="$XDG_CACHE_HOME"/node/history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/config"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"

command_exists npm && {
    PATH="$(npm config get prefix)/bin:$PATH"
    export PATH
}

#: }}}

#: Next.js {{{

export NEXT_TELEMETRY_DISABLED=1

#: }}}

#: Java {{{

#: To add a new Java version, for example, 11, run:
#: - macOS:
#:     jenv add "$(brew --prefix openjdk@11)/libexec/openjdk.jdk/Contents/Home"
#: - Linux:
#:     jenv add "$(brew --prefix openjdk@11)/libexec"
command_exists jenv && {
    export PATH="$HOME/.jenv/bin:$PATH"
    eval "$(jenv init -)"
}

#: }}}

#: Android Studio {{{

export ANDROID_HOME="$XDG_DATA_HOME"/android

#: }}}

#: Gradle {{{

export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle

#: }}}

#: .NET {{{

#: Opt out telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1

#: Change history file location
export DOTNET_CLI_HOME="$XDG_CACHE_HOME/dotnet"

#: }}}

#: Python {{{

#: Load Python startup file (usually for disabling history)
[ -f "$XDG_CONFIG_HOME/python/startup" ] &&
    export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/startup"

#: Disable keyring backend as some tools like `poetry` often throw errors when
#: trying to use in a non-GUI environment
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

#: Disable pip version check
export PIP_DISABLE_PIP_VERSION_CHECK=1

#: }}}

#: Poetry {{{

command_exists poetry && export POETRY_VIRTUALENVS_IN_PROJECT=1

#: }}}

#: IPython {{{

export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

#: }}}

#: Matplotlib {{{

export MPLCONFIGDIR="$XDG_CACHE_HOME/matplotlib"

#: }}}

#: Keras {{{

export KERAS_HOME="${XDG_STATE_HOME}/keras"

#: }}}

#: Gauge {{{

export GAUGE_HOME="$XDG_DATA_HOME/gauge"

#:}}}

#: Pyenv {{{

#: Require the following packages on Debian-based distros:
#: - build-essential
#: - libssl-dev
#: - zlib1g-dev
#: - libbz2-dev
#: - libreadline-dev
#: - libsqlite3-dev
#: - curl
#: - libncursesw5-dev
#: - xz-utils
#: - tk-dev
#: - libxml2-dev
#: - libxmlsec1-dev
#: - libffi-dev
#: - liblzma-dev

command_exists pyenv && {
    export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
    eval "$(pyenv init -)"
}

#: }}}

#: Docker {{{

export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

#: }}}

#: Minikube {{{

export MINIKUBE_HOME="$XDG_DATA_HOME"/minikube

#: }}}

#: CUDA {{{

export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

#: }}}

#: JetBrains Toolbox scripts {{{

#: On macOS, check if exists and not empty
toolbox_scripts="$HOME/Library/Application Support/JetBrains/Toolbox/scripts"
[ -d "$toolbox_scripts" ] && [ -n "$(ls -A "$toolbox_scripts")" ] &&
    export PATH="$toolbox_scripts:$PATH"
unset toolbox_scripts

#: }}}

#: Executable search paths, should be at the end to be prepended {{{

#: Set PATH so it includes user's private bin if it exists
[ -n "${PATH##*:$HOME/.local/bin:*}" ] && [ -d "$HOME/.local/bin" ] &&
    PATH="$HOME/.local/bin:$PATH"

#: }}}

unset -f include
