": vim: set fileencoding=utf-8 foldmethod=marker foldlevel=0:
": vim: set colorcolumn=81 nospell:

": This `.vimrc` is intended to be used with the non-plugin flavor of Vim.
": I don't really remember what features it requires, so let's compile Vim with
": most popular features enabled and you will be fine.
": I'm using Kitty terminal and Fira Code Retina Nerd Font and it's awesome.

": Let don't play with GUI
if has('gui_running')
    finish
endif

": Allow to run modelines with 5 top and bottom lines
set modelines=5

": Create a Autocmds holder for all the autocmds
": Reference: https://vi.stackexchange.com/q/9455
augroup MyAutocmdGroup
    autocmd!
augroup END

": Source configuration files
runtime config/general.vim
runtime config/interface.vim
runtime config/statusline.vim
runtime config/tabline.vim
runtime config/files.vim
runtime config/folding.vim
runtime config/netrw.vim
runtime config/completion.vim
runtime config/highlighting.vim
runtime config/keybindings.vim
runtime config/autocommands.vim

": Runtime
if filereadable("~/.config/vim/vimrc.local")
    runtime vimrc.local")
endif
