#: Configuration directory for applications respecting XDG specifications
export XDG_CONFIG_HOME="$HOME/.config"

#: GnuPG home
export GNUPGHOME="$HOME/.config/gnupg"

#: Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

#: Pyenv
eval "$(pyenv init -)"
